image: docker:latest
services:
  - docker:dind

stages:
  - build

Build image:
  stage: build
  script:
    - docker build --file=Dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - master
